@echo off
:: generated by Comonicon for the CLI Application baysor
setlocal
set JULIA_PROJECT=C:\Users\whl19\.julia\scratchspaces\cc9f9468-1fbe-11e9-0acf-e9460511877c\env
C:\Users\whl19\.julia\juliaup\julia-1.9.4+0.x64.w64.mingw32\bin\julia.exe ^
    --sysimage=C:\Users\whl19\.julia\scratchspaces\cc9f9468-1fbe-11e9-0acf-e9460511877c\sysimg\libbaysor.dll ^
    --startup-file=no ^
    --color=yes ^
    --compile=yes ^
    --optimize=2 ^
    -e "using Baysor; exit(Baysor.command_main())" %*
if %ERRORLEVEL% NEQ 0 exit /b %ERRORLEVEL%
endlocal
