# CLI params: `-c ./example/starmap.toml ./09012023-output/gene_identifided.csv ./09012023-output/DAPI_preprocessed.tif`
[data]
x = "x"
y = "y"
z = "z"
gene = "gene"
force_2d = false
min_molecules_per_gene = 1
exclude_genes = ""
min_molecules_per_cell = 1
min_molecules_per_segment = 1
confidence_nn_id = 5

[segmentation]
scale = -1.0
scale_std = "25%"
estimate_scale_from_centers = true
n_clusters = 4
prior_segmentation_confidence = 0.2
iters = 500
n_cells_init = 0
nuclei_genes = ""
cyto_genes = ""
new_component_weight = 0.2
new_component_fraction = 0.3

[plotting]
gene_composition_neigborhood = 0
min_pixels_per_cell = 15
